# Dependencies
markdown:         kramdown
highlighter:      rouge


# Setup
title:            'Quantum Information and Dynamics Workshop - Seoul 2025'
tagline:          'DYNQI 2025'
description:      'Workshop on quantum information and dynamics, taking place between 23 - 27 June 2025 in Seoul, Korea'
url:              ""
baseurl:          ""


author:
  name:           'Jong Yeon Lee'

paginate:         5

# Custom vars
version:          1.0.0

